# Generated by Django 3.0.7 on 2020-06-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('operacion', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=20)),
                ('medida', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('lote', models.CharField(max_length=20)),
                ('vencimiento', models.DateField()),
                ('deposito', models.CharField(max_length=30)),
                ('remito', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20)),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
    ]
