# Generated by Django 3.0.7 on 2020-06-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_App', '0002_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historial',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
