# Generated by Django 3.0.7 on 2020-06-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Gestion_App', '0003_auto_20200610_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
